### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cluster_poses'

### ISSUE THREAD

**Issue by aghaphd** [NVlabs/FoundationPose#89]
(my) root@5f6626e587fd:/workspace# python run_demo.py
Warp 1.0.2 initialized:
   CUDA Toolkit 11.5, Driver 11.4
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 3070 Ti Laptop GPU" (8 GiB, sm_86, mempool enabled)
   Kernel cache:
     /root/.cache/warp/1.0.2
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: 'Infinity'
debug: null
n_view: 1
run_id: 3wy8qqex
use_BN: true
exp_name: 2024-01-11-20-02-45
n_epochs: 62
save_dir: /home/ali/Downloads/FoundationPose/debug/2024-01-11-20-02-45/
use_mask: false
loss_type: pairwise_valid
optimizer: adam
batch_size: 64
crop_ratio: 1.1
enable_amp: true
use_normal: false
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
vis_interval: 1000
weight_decay: 0
normalize_xyz: true
resume_run_id: null
clip_grad_norm: 'Infinity'
lr_epoch_decay: 500
render_backend: nvdiffrast
train_num_pair: 5
lr_decay_epochs:
- 50
n_epochs_warmup: 1
make_pair_online: false
gradient_max_norm: 'Infinity'
max_step_per_epoch: 10000
n_rendering_workers: 1
save_epoch_interval: 100
n_dataloader_workers: 100
split_objects_across_gpus: true
ckpt_dir: /workspace/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth

[__init__()] self.h5_file:None
[__init__()] Using pretrained model from /workspace/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth
[__init__()] init done
[__init__()] welcome
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: .inf
debug: null
w_rot: 0.1
n_view: 1
run_id: null
use_BN: true
rot_rep: axis_angle
ckpt_dir: /workspace/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
exp_name: 2023-10-28-18-33-37
save_dir: /tmp/2023-10-28-18-33-37/
loss_type: l2
optimizer: adam
trans_rep: tracknet
batch_size: 64
crop_ratio: 1.2
use_normal: false
BN_momentum: 0.1
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
normal_uint8: false
vis_interval: 1000
weight_decay: 0
n_max_objects: null
normalize_xyz: true
clip_grad_norm: 'Infinity'
rot_normalizer: 0.3490658503988659
trans_normalizer:
- 0.019999999552965164
- 0.019999999552965164
- 0.05000000074505806
max_step_per_epoch: 25000
val_epoch_interval: 10
n_dataloader_workers: 60
enable_amp: true
use_mask: false

[__init__()] self.h5_file:
[__init__()] Using pretrained model from /workspace/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
[__init__()] init done
[reset_object()] self.diameter:0.19646325799497472, vox_size:0.009823162899748735
[reset_object()] self.pts:torch.Size([607, 3])
[reset_object()] reset done
[make_rotation_grid()] cam_in_obs:(42, 4, 4)
[make_rotation_grid()] rot_grid:(252, 4, 4)
Traceback (most recent call last):
  File "run_demo.py", line 41, in <module>
    est = FoundationPose(model_pts=mesh.vertices, model_normals=mesh.vertex_normals, mesh=mesh, scorer=scorer, refiner=refiner, debug_dir=debug_dir, debug=debug, glctx=glctx)
  File "/workspace/estimater.py", line 27, in __init__
    self.make_rotation_grid(min_n_views=40, inplane_step=60)
  File "/workspace/estimater.py", line 120, in make_rotation_grid
    rot_grid = mycpp.cluster_poses(30, 99999, rot_grid, self.symmetry_tfs.data.cpu().numpy())
AttributeError: 'NoneType' object has no attribute 'cluster_poses'
(my) root@5f6626e587fd:/workspace#

**Comment by aghaphd** [comment]
Before I run python run_demo.py, I have run the build_all.sh:

(my) root@5f6626e587fd:/workspace# bash build_all.sh 
CMake Error: The current CMakeCache.txt directory /workspace/mycpp/build/CMakeCache.txt is different than the directory /home/ali/Downloads/FoundationPose/mycpp/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/workspace/mycpp/CMakeLists.txt" does not match the source "/home/ali/Downloads/FoundationPose/mycpp/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
Obtaining file:///kaolin
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ipycanvas in /opt/conda/envs/my/lib/python3.8/site-packages/ipycanvas-0.13.1-py3.8.egg (from kaolin==0.15.0) (0.13.1)
Requirement already satisfied: ipyevents in /opt/conda/envs/my/lib/python3.8/site-packages/ipyevents-2.0.2-py3.8.egg (from kaolin==0.15.0) (2.0.2)
Requirement already satisfied: jupyter_client<8 in /opt/conda/envs/my/lib/python3.8/site-packages/jupyter_client-7.4.9-py3.8.egg (from kaolin==0.15.0) (7.4.9)
Requirement already satisfied: pyzmq<25 in /opt/conda/envs/my/lib/python3.8/site-packages/pyzmq-24.0.1-py3.8-linux-x86_64.egg (from kaolin==0.15.0) (24.0.1)
Requirement already satisfied: flask in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (3.0.3)
Requirement already satisfied: tornado in /opt/conda/envs/my/lib/python3.8/site-packages/tornado-6.4-py3.8-linux-x86_64.egg (from kaolin==0.15.0) (6.4)
Requirement already satisfied: comm>=0.1.3 in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (0.2.2)
Requirement already satisfied: numpy in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (1.24.3)
Requirement already satisfied: pybind11 in /opt/conda/envs/my/lib/python3.8/site-packages/pybind11-2.12.0-py3.8.egg (from kaolin==0.15.0) (2.12.0)
Requirement already satisfied: Pillow>=8.0.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (10.2.0)
Requirement already satisfied: tqdm>=4.51.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (4.66.2)
Requirement already satisfied: scipy in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (1.10.1)
Requirement already satisfied: pygltflib in /opt/conda/envs/my/lib/python3.8/site-packages/pygltflib-1.16.2-py3.8.egg (from kaolin==0.15.0) (1.16.2)
Requirement already satisfied: usd-core<=23.5 in /opt/conda/envs/my/lib/python3.8/site-packages/usd_core-23.5-py3.8-linux-x86_64.egg (from kaolin==0.15.0) (23.5)
Requirement already satisfied: ipython<8.13 in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (8.12.3)
Requirement already satisfied: traitlets>=4 in /opt/conda/envs/my/lib/python3.8/site-packages (from comm>=0.1.3->kaolin==0.15.0) (5.14.3)
Requirement already satisfied: backcall in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (0.2.0)
Requirement already satisfied: decorator in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (0.19.1)
Requirement already satisfied: matplotlib-inline in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (0.1.7)
Requirement already satisfied: pickleshare in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (2.17.2)
Requirement already satisfied: stack-data in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (0.6.3)
Requirement already satisfied: typing-extensions in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (4.9.0)
Requirement already satisfied: pexpect>4.3 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (4.9.0)
Requirement already satisfied: entrypoints in /opt/conda/envs/my/lib/python3.8/site-packages/entrypoints-0.4-py3.8.egg (from jupyter_client<8->kaolin==0.15.0) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /opt/conda/envs/my/lib/python3.8/site-packages (from jupyter_client<8->kaolin==0.15.0) (5.7.2)
Requirement already satisfied: nest-asyncio>=1.5.4 in /opt/conda/envs/my/lib/python3.8/site-packages (from jupyter_client<8->kaolin==0.15.0) (1.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/envs/my/lib/python3.8/site-packages (from jupyter_client<8->kaolin==0.15.0) (2.9.0.post0)
Requirement already satisfied: Werkzeug>=3.0.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (3.0.2)
Requirement already satisfied: Jinja2>=3.1.2 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (3.1.3)
Requirement already satisfied: itsdangerous>=2.1.2 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (1.7.0)
Requirement already satisfied: importlib-metadata>=3.6.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (7.1.0)
Requirement already satisfied: ipywidgets<9,>=7.6.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipycanvas->kaolin==0.15.0) (8.1.2)
Requirement already satisfied: dataclasses-json>=0.0.25 in /opt/conda/envs/my/lib/python3.8/site-packages/dataclasses_json-0.6.4-py3.8.egg (from pygltflib->kaolin==0.15.0) (0.6.4)
Requirement already satisfied: deprecated in /opt/conda/envs/my/lib/python3.8/site-packages/Deprecated-1.2.14-py3.8.egg (from pygltflib->kaolin==0.15.0) (1.2.14)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /opt/conda/envs/my/lib/python3.8/site-packages/marshmallow-3.21.1-py3.8.egg (from dataclasses-json>=0.0.25->pygltflib->kaolin==0.15.0) (3.21.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /opt/conda/envs/my/lib/python3.8/site-packages/typing_inspect-0.9.0-py3.8.egg (from dataclasses-json>=0.0.25->pygltflib->kaolin==0.15.0) (0.9.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/envs/my/lib/python3.8/site-packages (from importlib-metadata>=3.6.0->flask->kaolin==0.15.0) (3.18.1)
Requirement already satisfied: widgetsnbextension~=4.0.10 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipywidgets<9,>=7.6.0->ipycanvas->kaolin==0.15.0) (4.0.10)
Requirement already satisfied: jupyterlab-widgets~=3.0.10 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipywidgets<9,>=7.6.0->ipycanvas->kaolin==0.15.0) (3.0.10)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /opt/conda/envs/my/lib/python3.8/site-packages (from jedi>=0.16->ipython<8.13->kaolin==0.15.0) (0.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from Jinja2>=3.1.2->flask->kaolin==0.15.0) (2.1.5)
Requirement already satisfied: platformdirs>=2.5 in /opt/conda/envs/my/lib/python3.8/site-packages (from jupyter-core>=4.9.2->jupyter_client<8->kaolin==0.15.0) (4.2.1)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/envs/my/lib/python3.8/site-packages (from pexpect>4.3->ipython<8.13->kaolin==0.15.0) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/envs/my/lib/python3.8/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython<8.13->kaolin==0.15.0) (0.2.13)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/my/lib/python3.8/site-packages (from python-dateutil>=2.8.2->jupyter_client<8->kaolin==0.15.0) (1.16.0)
Requirement already satisfied: wrapt<2,>=1.10 in /opt/conda/envs/my/lib/python3.8/site-packages/wrapt-1.16.0-py3.8.egg (from deprecated->pygltflib->kaolin==0.15.0) (1.16.0)
Requirement already satisfied: executing>=1.2.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from stack-data->ipython<8.13->kaolin==0.15.0) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from stack-data->ipython<8.13->kaolin==0.15.0) (2.4.1)
Requirement already satisfied: pure-eval in /opt/conda/envs/my/lib/python3.8/site-packages (from stack-data->ipython<8.13->kaolin==0.15.0) (0.2.2)
Requirement already satisfied: packaging>=17.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json>=0.0.25->pygltflib->kaolin==0.15.0) (24.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /opt/conda/envs/my/lib/python3.8/site-packages/mypy_extensions-1.0.0-py3.8.egg (from typing-inspect<1,>=0.4.0->dataclasses-json>=0.0.25->pygltflib->kaolin==0.15.0) (1.0.0)
Installing collected packages: kaolin
  Running setup.py develop for kaolin
Successfully installed kaolin-0.15.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Obtaining file:///workspace/bundlesdf/mycuda
  Preparing metadata (setup.py) ... done
Installing collected packages: common
  Running setup.py develop for common
Successfully installed common-0.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by wenbowen123** [comment]
![image](https://github.com/NVlabs/FoundationPose/assets/23078192/23bee496-2eb7-47c2-a655-9b23b4aae746)
did you run this?

**Comment by aghaphd** [comment]
Yes, I did.

**Comment by wenbowen123** [comment]
Then it should generate a .so file under the `mycpp/build` folder. Do you have it?

**Comment by aghaphd** [comment]
I will check it out and let you know.

Thank you so much for your time and support.

**Comment by aghaphd** [comment]
![Screenshot from 2024-04-26 02-17-11](https://github.com/NVlabs/FoundationPose/assets/87492339/d1f87fc7-db39-46d3-a846-64c9076c2c66)
yes, I have the mycpp.cpython-39-x86_64-linux-gnu.so inside mycpp/build.

**Comment by wenbowen123** [comment]
if you cd to `mycpp/build`, then python, then `import mycpp`, what happens?

**Comment by aghaphd** [comment]
(my) root@5f6626e587fd:/workspace# ls
LICENSE             bundlesdf      kaolin                 run_demo.py
Utils.py            datareader.py  learning               run_linemod.py
__pycache__         debug          mycpp                  run_ycb_video.py
assets              demo_data      offscreen_renderer.py  weights
build_all.sh        docker         readme.md
build_all_conda.sh  estimater.py   requirements.txt
(my) root@5f6626e587fd:/workspace# cd mycpp
(my) root@5f6626e587fd:/workspace/mycpp# cd build
(my) root@5f6626e587fd:/workspace/mycpp/build# python
Python 3.8.19 (default, Mar 20 2024, 19:58:24) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mycpp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mycpp'
>>> 
I see there is a problem?

**Comment by wenbowen123** [comment]
> CMake Error: The current CMakeCache.txt directory /workspace/mycpp/build/CMakeCache.txt is different than the directory /home/ali/Downloads/FoundationPose/mycpp/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt

This is from your error log. It seems like you mixed the paths. I'd suggest mount your local `/home/ali/Downloads/FoundationPose` to docker and rebuild

**Comment by aghaphd** [comment]
Thank you so much for the guidance, the problem above is solved and I will close the issue.

I faced another problem, will try to solve it: 

(my) root@5f6626e587fd:/workspace# python run_demo.py
Warp 1.0.2 initialized:
   CUDA Toolkit 11.5, Driver 11.4
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 3070 Ti Laptop GPU" (8 GiB, sm_86, mempool enabled)
   Kernel cache:
     /root/.cache/warp/1.0.2
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: 'Infinity'
debug: null
n_view: 1
run_id: 3wy8qqex
use_BN: true
exp_name: 2024-01-11-20-02-45
n_epochs: 62
save_dir: /home/ali/Downloads/FoundationPose/debug/2024-01-11-20-02-45/
use_mask: false
loss_type: pairwise_valid
optimizer: adam
batch_size: 64
crop_ratio: 1.1
enable_amp: true
use_normal: false
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
vis_interval: 1000
weight_decay: 0
normalize_xyz: true
resume_run_id: null
clip_grad_norm: 'Infinity'
lr_epoch_decay: 500
render_backend: nvdiffrast
train_num_pair: 5
lr_decay_epochs:
- 50
n_epochs_warmup: 1
make_pair_online: false
gradient_max_norm: 'Infinity'
max_step_per_epoch: 10000
n_rendering_workers: 1
save_epoch_interval: 100
n_dataloader_workers: 100
split_objects_across_gpus: true
ckpt_dir: /workspace/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth

[__init__()] self.h5_file:None
[__init__()] Using pretrained model from /workspace/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth
[__init__()] init done
[__init__()] welcome
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: .inf
debug: null
w_rot: 0.1
n_view: 1
run_id: null
use_BN: true
rot_rep: axis_angle
ckpt_dir: /workspace/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
exp_name: 2023-10-28-18-33-37
save_dir: /tmp/2023-10-28-18-33-37/
loss_type: l2
optimizer: adam
trans_rep: tracknet
batch_size: 64
crop_ratio: 1.2
use_normal: false
BN_momentum: 0.1
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
normal_uint8: false
vis_interval: 1000
weight_decay: 0
n_max_objects: null
normalize_xyz: true
clip_grad_norm: 'Infinity'
rot_normalizer: 0.3490658503988659
trans_normalizer:
- 0.019999999552965164
- 0.019999999552965164
- 0.05000000074505806
max_step_per_epoch: 25000
val_epoch_interval: 10
n_dataloader_workers: 60
enable_amp: true
use_mask: false

[__init__()] self.h5_file:
[__init__()] Using pretrained model from /workspace/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
[__init__()] init done
[reset_object()] self.diameter:0.19646325799497472, vox_size:0.009823162899748735
[reset_object()] self.pts:torch.Size([607, 3])
[reset_object()] reset done
[make_rotation_grid()] cam_in_obs:(42, 4, 4)
[make_rotation_grid()] rot_grid:(252, 4, 4)
num original candidates = 252
num of pose after clustering: 252
[make_rotation_grid()] after cluster, rot_grid:(252, 4, 4)
[make_rotation_grid()] self.rot_grid: torch.Size([252, 4, 4])
[<module>()] estimator initialization done
[<module>()] i:0
[register()] Welcome
Module Utils load on device 'cuda:0' took 5.82 ms
[register()] poses:(252, 4, 4)
[register()] after viewpoint, add_errs min:-1.0
[predict()] ob_in_cams:(252, 4, 4)
[predict()] self.cfg.use_normal:False
[predict()] trans_normalizer:[0.019999999552965164, 0.019999999552965164, 0.05000000074505806], rot_normalizer:0.3490658503988659
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] ob_in_cams:(252, 4, 4)
[predict()] self.cfg.use_normal:False
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] pose batch data done
[find_best_among_pairs()] pose_data.rgbAs.shape[0]: 252
[predict()] forward done
[register()] final, add_errs min:-1.0
[register()] sort ids:tensor([ 98,   0,   6,   7,  30,  31,  67,  72,  73, 102, 103, 127, 133, 168,
        186, 199, 223, 241, 242,   1,  68,  97, 109, 169, 224,  96, 126, 145,
        198, 132, 187, 228,  24,  25,  55,  78,  79,  84, 150, 229, 234,  12,
         13,  18,  19,  85,  90,  91,  92, 112, 115, 120, 121, 151, 175, 176,
        181, 182,  56, 108, 114, 236,  86,  74, 104, 235, 247,  54, 193, 111,
        188, 205,  66,  26, 174,  80, 222,  14, 230, 163, 248, 194,  32,  69,
        211, 144, 231, 245, 113, 170,  81, 204,  57, 110, 131, 106,  61, 192,
        246, 196,  49, 178, 240, 171,  53, 149, 180, 123,  15,  48, 172,  39,
         88,  94, 135, 155, 117, 191,   9,  45,  65,  87, 147,  52, 154, 221,
        119, 202, 207, 214,  10,  58, 148, 166,  29, 161,  35,  64, 226,  16,
         23, 208, 232, 251,  77, 105, 179,  70, 203, 250,   5,  60, 141, 125,
        137, 183, 197, 158, 107, 165, 209, 243,  75, 129, 160, 244,  11,  59,
         83, 215,  82, 184, 210,  20, 100, 218,  17,  27, 140, 177, 227,  34,
         47, 136,  50,  62,  71, 122, 143, 212, 213,   2,  51,  76, 118, 124,
        138, 220, 238, 239, 249,   4,  37,  63, 167, 195,  22,  41,  46,  99,
        139,  40,  93, 130, 190, 201,   3,  21,  95, 142, 225, 219, 101, 153,
        159, 164, 216,  44, 185, 116, 233, 162,  43, 200,  28, 134,   8,  89,
        128, 152, 173,  38, 146, 189, 217,  33, 237, 156,  42, 157, 206,  36])
[register()] sorted scores:tensor([77.7969, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812,
        77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812,
        77.7812, 77.7812, 77.7812, 77.7656, 77.7656, 77.7656, 77.7656, 77.7656,
        77.7656, 77.7500, 77.7500, 77.7500, 77.7500, 77.7344, 77.6562, 77.6250,
        77.6094, 77.6094, 77.6094, 77.6094, 77.6094, 77.6094, 77.6094, 77.6094,
        77.6094, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938,
        77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938,
        77.5938, 77.5938, 77.5781, 77.5781, 77.5781, 77.5625, 77.5469, 77.5312,
        77.5312, 77.5312, 77.5312, 77.5156, 77.5156, 77.5000, 77.5000, 77.4844,
        77.4688, 77.3281, 77.2812, 77.2656, 77.2656, 77.1719, 77.1719, 77.1562,
        77.1562, 77.1094, 77.0938, 77.0938, 77.0938, 77.0625, 77.0625, 77.0625,
        77.0469, 77.0469, 77.0156, 77.0156, 76.9844, 76.9844, 76.9531, 76.9219,
        76.8906, 76.8750, 76.8750, 76.8594, 76.8438, 76.8438, 76.8438, 76.8125,
        76.7969, 76.7969, 76.7969, 76.7500, 76.7188, 76.7188, 76.7188, 76.6875,
        76.6562, 76.6562, 76.6562, 76.6406, 76.6094, 76.6094, 76.5938, 76.5781,
        76.5625, 76.5625, 76.5625, 76.5469, 76.5469, 76.5469, 76.5312, 76.5312,
        76.5312, 76.5312, 76.5156, 76.5156, 76.5156, 76.5156, 76.5000, 76.5000,
        76.4844, 76.4844, 76.4844, 76.4688, 76.4688, 76.4688, 76.4688, 76.4688,
        76.4531, 76.4531, 76.4531, 76.4375, 76.4375, 76.4375, 76.4219, 76.4219,
        76.4219, 76.3906, 76.3906, 76.3906, 76.3906, 76.3750, 76.3594, 76.3594,
        76.3594, 76.3594, 76.3438, 76.3438, 76.3125, 76.3125, 76.2969, 76.2969,
        76.2969, 76.2969, 76.2812, 76.2812, 76.2812, 76.2656, 76.2656, 76.2656,
        76.2500, 76.2500, 76.2500, 76.2500, 76.2500, 76.2344, 76.2344, 76.2344,
        76.2188, 76.2188, 76.2188, 76.2188, 76.2188, 76.2188, 76.2188, 76.2031,
        76.2031, 76.2031, 76.2031, 76.2031, 76.2031, 76.2031, 76.2031, 76.2031,
        76.2031, 76.1875, 76.1875, 76.1875, 76.1875, 76.1875, 76.1719, 76.1719,
        76.1719, 76.1719, 76.1719, 76.1562, 76.1562, 76.1562, 76.1562, 76.1406,
        76.1250, 76.1250, 76.1250, 76.1250, 76.1250, 76.1094, 76.0938, 76.0938,
        76.0938, 76.0938, 76.0938, 76.0781, 76.0781, 76.0625, 76.0625, 76.0469,
        76.0312, 76.0312, 76.0156, 76.0156, 76.0000, 76.0000, 75.9844, 75.9844,
        75.9844, 75.9688, 75.9219, 75.9219, 75.9219, 75.9062, 75.9062, 75.8906,
        75.8594, 75.8594, 75.8594, 75.8125])
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/opt/conda/envs/my/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)

**Comment by MY-CODE-1981** [comment]
CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib/python3.9/site-packages/pybind11/share/cmake/pybind11 bash build_all_conda.sh
After this procedure, a .so file will be created under mycpp/build. If its name is not mycpp.so, an error will occur when executing mycpp.cluster_poses in estimator.py.

The solution is simple: just rename the .so file to mycpp.so. In my case, the name was as follows, and changing it to mycpp.so resolved the issue:
mycpp.cpython-39-x86_64-linux-gnu.so

**Comment by ahiyantra** [comment]
@MY-CODE-1981
Unfortunately, your solution didn't work for me. I went into "mycpp/build" and used "import mycpp" with python just to be sure but there was no module import error for it. Despite that, i still can't use "run_demo[dot]py" without getting the "nonetype" error.

**Comment by ahiyantra** [comment]
> Thank you so much for the guidance, the problem above is solved and I will close the issue.
> 
> I faced another problem, will try to solve it:
> 
> (my) root@5f6626e587fd:/workspace# python run_demo.py Warp 1.0.2 initialized: CUDA Toolkit 11.5, Driver 11.4 Devices: "cpu" : "x86_64" "cuda:0" : "NVIDIA GeForce RTX 3070 Ti Laptop GPU" (8 GiB, sm_86, mempool enabled) Kernel cache: /root/.cache/warp/1.0.2 [**init**()] self.cfg: lr: 0.0001 c_in: 6 zfar: 'Infinity' debug: null n_view: 1 run_id: 3wy8qqex use_BN: true exp_name: 2024-01-11-20-02-45 n_epochs: 62 save_dir: /home/ali/Downloads/FoundationPose/debug/2024-01-11-20-02-45/ use_mask: false loss_type: pairwise_valid optimizer: adam batch_size: 64 crop_ratio: 1.1 enable_amp: true use_normal: false max_num_key: null warmup_step: -1 input_resize:
> 
> * 160
> * 160
>   max_step_val: 1000
>   vis_interval: 1000
>   weight_decay: 0
>   normalize_xyz: true
>   resume_run_id: null
>   clip_grad_norm: 'Infinity'
>   lr_epoch_decay: 500
>   render_backend: nvdiffrast
>   train_num_pair: 5
>   lr_decay_epochs:
> * 50
>   n_epochs_warmup: 1
>   make_pair_online: false
>   gradient_max_norm: 'Infinity'
>   max_step_per_epoch: 10000
>   n_rendering_workers: 1
>   save_epoch_interval: 100
>   n_dataloader_workers: 100
>   split_objects_across_gpus: true
>   ckpt_dir: /workspace/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth
> 
> [**init**()] self.h5_file:None [**init**()] Using pretrained model from /workspace/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth [**init**()] init done [**init**()] welcome [**init**()] self.cfg: lr: 0.0001 c_in: 6 zfar: .inf debug: null w_rot: 0.1 n_view: 1 run_id: null use_BN: true rot_rep: axis_angle ckpt_dir: /workspace/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth exp_name: 2023-10-28-18-33-37 save_dir: /tmp/2023-10-28-18-33-37/ loss_type: l2 optimizer: adam trans_rep: tracknet batch_size: 64 crop_ratio: 1.2 use_normal: false BN_momentum: 0.1 max_num_key: null warmup_step: -1 input_resize:
> 
> * 160
> * 160
>   max_step_val: 1000
>   normal_uint8: false
>   vis_interval: 1000
>   weight_decay: 0
>   n_max_objects: null
>   normalize_xyz: true
>   clip_grad_norm: 'Infinity'
>   rot_normalizer: 0.3490658503988659
>   trans_normalizer:
> * 0.019999999552965164
> * 0.019999999552965164
> * 0.05000000074505806
>   max_step_per_epoch: 25000
>   val_epoch_interval: 10
>   n_dataloader_workers: 60
>   enable_amp: true
>   use_mask: false
> 
> [**init**()] self.h5_file: [**init**()] Using pretrained model from /workspace/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth [**init**()] init done [reset_object()] self.diameter:0.19646325799497472, vox_size:0.009823162899748735 [reset_object()] self.pts:torch.Size([607, 3]) [reset_object()] reset done [make_rotation_grid()] cam_in_obs:(42, 4, 4) [make_rotation_grid()] rot_grid:(252, 4, 4) num original candidates = 252 num of pose after clustering: 252 [make_rotation_grid()] after cluster, rot_grid:(252, 4, 4) [make_rotation_grid()] self.rot_grid: torch.Size([252, 4, 4]) [()] estimator initialization done [()] i:0 [register()] Welcome Module Utils load on device 'cuda:0' took 5.82 ms [register()] poses:(252, 4, 4) [register()] after viewpoint, add_errs min:-1.0 [predict()] ob_in_cams:(252, 4, 4) [predict()] self.cfg.use_normal:False [predict()] trans_normalizer:[0.019999999552965164, 0.019999999552965164, 0.05000000074505806], rot_normalizer:0.3490658503988659 [predict()] making cropped data [make_crop_data_batch()] Welcome make_crop_data_batch [make_crop_data_batch()] make tf_to_crops done [make_crop_data_batch()] render done [make_crop_data_batch()] warp done [make_crop_data_batch()] pose batch data done [predict()] forward start [predict()] forward done [predict()] making cropped data [make_crop_data_batch()] Welcome make_crop_data_batch [make_crop_data_batch()] make tf_to_crops done [make_crop_data_batch()] render done [make_crop_data_batch()] warp done [make_crop_data_batch()] pose batch data done [predict()] forward start [predict()] forward done [predict()] making cropped data [make_crop_data_batch()] Welcome make_crop_data_batch [make_crop_data_batch()] make tf_to_crops done [make_crop_data_batch()] render done [make_crop_data_batch()] warp done [make_crop_data_batch()] pose batch data done [predict()] forward start [predict()] forward done [predict()] making cropped data [make_crop_data_batch()] Welcome make_crop_data_batch [make_crop_data_batch()] make tf_to_crops done [make_crop_data_batch()] render done [make_crop_data_batch()] warp done [make_crop_data_batch()] pose batch data done [predict()] forward start [predict()] forward done [predict()] making cropped data [make_crop_data_batch()] Welcome make_crop_data_batch [make_crop_data_batch()] make tf_to_crops done [make_crop_data_batch()] render done [make_crop_data_batch()] warp done [make_crop_data_batch()] pose batch data done [predict()] forward start [predict()] forward done [predict()] ob_in_cams:(252, 4, 4) [predict()] self.cfg.use_normal:False [predict()] making cropped data [make_crop_data_batch()] Welcome make_crop_data_batch [make_crop_data_batch()] make tf_to_crops done [make_crop_data_batch()] render done [make_crop_data_batch()] pose batch data done [find_best_among_pairs()] pose_data.rgbAs.shape[0]: 252 [predict()] forward done [register()] final, add_errs min:-1.0 [register()] sort ids:tensor([ 98, 0, 6, 7, 30, 31, 67, 72, 73, 102, 103, 127, 133, 168, 186, 199, 223, 241, 242, 1, 68, 97, 109, 169, 224, 96, 126, 145, 198, 132, 187, 228, 24, 25, 55, 78, 79, 84, 150, 229, 234, 12, 13, 18, 19, 85, 90, 91, 92, 112, 115, 120, 121, 151, 175, 176, 181, 182, 56, 108, 114, 236, 86, 74, 104, 235, 247, 54, 193, 111, 188, 205, 66, 26, 174, 80, 222, 14, 230, 163, 248, 194, 32, 69, 211, 144, 231, 245, 113, 170, 81, 204, 57, 110, 131, 106, 61, 192, 246, 196, 49, 178, 240, 171, 53, 149, 180, 123, 15, 48, 172, 39, 88, 94, 135, 155, 117, 191, 9, 45, 65, 87, 147, 52, 154, 221, 119, 202, 207, 214, 10, 58, 148, 166, 29, 161, 35, 64, 226, 16, 23, 208, 232, 251, 77, 105, 179, 70, 203, 250, 5, 60, 141, 125, 137, 183, 197, 158, 107, 165, 209, 243, 75, 129, 160, 244, 11, 59, 83, 215, 82, 184, 210, 20, 100, 218, 17, 27, 140, 177, 227, 34, 47, 136, 50, 62, 71, 122, 143, 212, 213, 2, 51, 76, 118, 124, 138, 220, 238, 239, 249, 4, 37, 63, 167, 195, 22, 41, 46, 99, 139, 40, 93, 130, 190, 201, 3, 21, 95, 142, 225, 219, 101, 153, 159, 164, 216, 44, 185, 116, 233, 162, 43, 200, 28, 134, 8, 89, 128, 152, 173, 38, 146, 189, 217, 33, 237, 156, 42, 157, 206, 36]) [register()] sorted scores:tensor([77.7969, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7812, 77.7656, 77.7656, 77.7656, 77.7656, 77.7656, 77.7656, 77.7500, 77.7500, 77.7500, 77.7500, 77.7344, 77.6562, 77.6250, 77.6094, 77.6094, 77.6094, 77.6094, 77.6094, 77.6094, 77.6094, 77.6094, 77.6094, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5938, 77.5781, 77.5781, 77.5781, 77.5625, 77.5469, 77.5312, 77.5312, 77.5312, 77.5312, 77.5156, 77.5156, 77.5000, 77.5000, 77.4844, 77.4688, 77.3281, 77.2812, 77.2656, 77.2656, 77.1719, 77.1719, 77.1562, 77.1562, 77.1094, 77.0938, 77.0938, 77.0938, 77.0625, 77.0625, 77.0625, 77.0469, 77.0469, 77.0156, 77.0156, 76.9844, 76.9844, 76.9531, 76.9219, 76.8906, 76.8750, 76.8750, 76.8594, 76.8438, 76.8438, 76.8438, 76.8125, 76.7969, 76.7969, 76.7969, 76.7500, 76.7188, 76.7188, 76.7188, 76.6875, 76.6562, 76.6562, 76.6562, 76.6406, 76.6094, 76.6094, 76.5938, 76.5781, 76.5625, 76.5625, 76.5625, 76.5469, 76.5469, 76.5469, 76.5312, 76.5312, 76.5312, 76.5312, 76.5156, 76.5156, 76.5156, 76.5156, 76.5000, 76.5000, 76.4844, 76.4844, 76.4844, 76.4688, 76.4688, 76.4688, 76.4688, 76.4688, 76.4531, 76.4531, 76.4531, 76.4375, 76.4375, 76.4375, 76.4219, 76.4219, 76.4219, 76.3906, 76.3906, 76.3906, 76.3906, 76.3750, 76.3594, 76.3594, 76.3594, 76.3594, 76.3438, 76.3438, 76.3125, 76.3125, 76.2969, 76.2969, 76.2969, 76.2969, 76.2812, 76.2812, 76.2812, 76.2656, 76.2656, 76.2656, 76.2500, 76.2500, 76.2500, 76.2500, 76.2500, 76.2344, 76.2344, 76.2344, 76.2188, 76.2188, 76.2188, 76.2188, 76.2188, 76.2188, 76.2188, 76.2031, 76.2031, 76.2031, 76.2031, 76.2031, 76.2031, 76.2031, 76.2031, 76.2031, 76.2031, 76.1875, 76.1875, 76.1875, 76.1875, 76.1875, 76.1719, 76.1719, 76.1719, 76.1719, 76.1719, 76.1562, 76.1562, 76.1562, 76.1562, 76.1406, 76.1250, 76.1250, 76.1250, 76.1250, 76.1250, 76.1094, 76.0938, 76.0938, 76.0938, 76.0938, 76.0938, 76.0781, 76.0781, 76.0625, 76.0625, 76.0469, 76.0312, 76.0312, 76.0156, 76.0156, 76.0000, 76.0000, 75.9844, 75.9844, 75.9844, 75.9688, 75.9219, 75.9219, 75.9219, 75.9062, 75.9062, 75.8906, 75.8594, 75.8594, 75.8594, 75.8125]) qt.qpa.xcb: could not connect to display qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/opt/conda/envs/my/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: xcb.
> 
> Aborted (core dumped)

Did you find the solution for this new issue? I'm facing the same issue now.
